---

- name: Set masters to unschedulable
  lineinfile:
    path: '{{ install_dir }}/manifests/cluster-scheduler-02-config.yml'
    regexp: "^mastersSchedulable"
    line: "  mastersSchedulable: false"

- name: Create ignition-configs
  shell: openshift-install create ignition-configs --dir={{ install_dir }}

- name: Copy bootstrap.ign to registry node
  shell: 'scp bootstrap.ign {{ utility_node }}:'

- name: Change mode of bootstrap.ign
  shell: 'ssh {{ utility_node }} chmod 644 bootstrap.ign'

- name: Move bootstrap.ign to /var/www/html
  shell: 'ssh {{ utility_node }} sudo mv bootstrap.ign /var/www/html'

- name: Use restorecon for SELinux labeling
  shell: 'ssh {{ utility_node }} sudo restorecon /var/www/html/bootstrap.ign'

- name: Generate file to point to bootstrap.ign on Utility node
  shell: 'cat << EOF > "{{ install_dir }}/{{ INFRA_ID }}-bootstrap-ignition.json"
{
  "ignition": {
    "config": {
      "append": [
        {
          "source": "http://{{ utility_node }}/bootstrap.ign",
          "verification": {}
        }
      ]
    },
    "security": {},
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {}
}
EOF'
